/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProduitRouteImport } from './routes/produit'
import { Route as ProRouteImport } from './routes/pro'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnProduitRouteImport } from './routes/en/produit'
import { Route as EnProRouteImport } from './routes/en/pro'
import { Route as EnMentionsLegalesRouteImport } from './routes/en/mentions-legales'
import { Route as EnFaqRouteImport } from './routes/en/faq'
import { Route as EnConfidentialiteRouteImport } from './routes/en/confidentialite'
import { Route as EnBlogRouteImport } from './routes/en/blog'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as DeProduitRouteImport } from './routes/de/produit'
import { Route as DeProRouteImport } from './routes/de/pro'
import { Route as DeMentionsLegalesRouteImport } from './routes/de/mentions-legales'
import { Route as DeFaqRouteImport } from './routes/de/faq'
import { Route as DeConfidentialiteRouteImport } from './routes/de/confidentialite'
import { Route as DeBlogRouteImport } from './routes/de/blog'
import { Route as DeIndexRouteImport } from './routes/de/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitRoute = ProduitRouteImport.update({
  id: '/produit',
  path: '/produit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProduitRoute = EnProduitRouteImport.update({
  id: '/en/produit',
  path: '/en/produit',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProRoute = EnProRouteImport.update({
  id: '/en/pro',
  path: '/en/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMentionsLegalesRoute = EnMentionsLegalesRouteImport.update({
  id: '/en/mentions-legales',
  path: '/en/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const EnFaqRoute = EnFaqRouteImport.update({
  id: '/en/faq',
  path: '/en/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnConfidentialiteRoute = EnConfidentialiteRouteImport.update({
  id: '/en/confidentialite',
  path: '/en/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const EnBlogRoute = EnBlogRouteImport.update({
  id: '/en/blog',
  path: '/en/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const DeProduitRoute = DeProduitRouteImport.update({
  id: '/de/produit',
  path: '/de/produit',
  getParentRoute: () => rootRouteImport,
} as any)
const DeProRoute = DeProRouteImport.update({
  id: '/de/pro',
  path: '/de/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const DeMentionsLegalesRoute = DeMentionsLegalesRouteImport.update({
  id: '/de/mentions-legales',
  path: '/de/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const DeFaqRoute = DeFaqRouteImport.update({
  id: '/de/faq',
  path: '/de/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeConfidentialiteRoute = DeConfidentialiteRouteImport.update({
  id: '/de/confidentialite',
  path: '/de/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const DeBlogRoute = DeBlogRouteImport.update({
  id: '/de/blog',
  path: '/de/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/de/',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/de': typeof DeIndexRoute
  '/de/blog': typeof DeBlogRoute
  '/de/confidentialite': typeof DeConfidentialiteRoute
  '/de/faq': typeof DeFaqRoute
  '/de/mentions-legales': typeof DeMentionsLegalesRoute
  '/de/pro': typeof DeProRoute
  '/de/produit': typeof DeProduitRoute
  '/en': typeof EnIndexRoute
  '/en/blog': typeof EnBlogRoute
  '/en/confidentialite': typeof EnConfidentialiteRoute
  '/en/faq': typeof EnFaqRoute
  '/en/mentions-legales': typeof EnMentionsLegalesRoute
  '/en/pro': typeof EnProRoute
  '/en/produit': typeof EnProduitRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pro': typeof ProRoute
  '/produit': typeof ProduitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/de': typeof DeIndexRoute
  '/de/blog': typeof DeBlogRoute
  '/de/confidentialite': typeof DeConfidentialiteRoute
  '/de/faq': typeof DeFaqRoute
  '/de/mentions-legales': typeof DeMentionsLegalesRoute
  '/de/pro': typeof DeProRoute
  '/de/produit': typeof DeProduitRoute
  '/en': typeof EnIndexRoute
  '/en/blog': typeof EnBlogRoute
  '/en/confidentialite': typeof EnConfidentialiteRoute
  '/en/faq': typeof EnFaqRoute
  '/en/mentions-legales': typeof EnMentionsLegalesRoute
  '/en/pro': typeof EnProRoute
  '/en/produit': typeof EnProduitRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pro': typeof ProRoute
  '/produit': typeof ProduitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/de/': typeof DeIndexRoute
  '/de/blog': typeof DeBlogRoute
  '/de/confidentialite': typeof DeConfidentialiteRoute
  '/de/faq': typeof DeFaqRoute
  '/de/mentions-legales': typeof DeMentionsLegalesRoute
  '/de/pro': typeof DeProRoute
  '/de/produit': typeof DeProduitRoute
  '/en/': typeof EnIndexRoute
  '/en/blog': typeof EnBlogRoute
  '/en/confidentialite': typeof EnConfidentialiteRoute
  '/en/faq': typeof EnFaqRoute
  '/en/mentions-legales': typeof EnMentionsLegalesRoute
  '/en/pro': typeof EnProRoute
  '/en/produit': typeof EnProduitRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pro': typeof ProRoute
  '/produit': typeof ProduitRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/confidentialite'
    | '/de'
    | '/de/blog'
    | '/de/confidentialite'
    | '/de/faq'
    | '/de/mentions-legales'
    | '/de/pro'
    | '/de/produit'
    | '/en'
    | '/en/blog'
    | '/en/confidentialite'
    | '/en/faq'
    | '/en/mentions-legales'
    | '/en/pro'
    | '/en/produit'
    | '/faq'
    | '/mentions-legales'
    | '/pro'
    | '/produit'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/confidentialite'
    | '/de'
    | '/de/blog'
    | '/de/confidentialite'
    | '/de/faq'
    | '/de/mentions-legales'
    | '/de/pro'
    | '/de/produit'
    | '/en'
    | '/en/blog'
    | '/en/confidentialite'
    | '/en/faq'
    | '/en/mentions-legales'
    | '/en/pro'
    | '/en/produit'
    | '/faq'
    | '/mentions-legales'
    | '/pro'
    | '/produit'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/confidentialite'
    | '/de/'
    | '/de/blog'
    | '/de/confidentialite'
    | '/de/faq'
    | '/de/mentions-legales'
    | '/de/pro'
    | '/de/produit'
    | '/en/'
    | '/en/blog'
    | '/en/confidentialite'
    | '/en/faq'
    | '/en/mentions-legales'
    | '/en/pro'
    | '/en/produit'
    | '/faq'
    | '/mentions-legales'
    | '/pro'
    | '/produit'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DeIndexRoute: typeof DeIndexRoute
  DeBlogRoute: typeof DeBlogRoute
  DeConfidentialiteRoute: typeof DeConfidentialiteRoute
  DeFaqRoute: typeof DeFaqRoute
  DeMentionsLegalesRoute: typeof DeMentionsLegalesRoute
  DeProRoute: typeof DeProRoute
  DeProduitRoute: typeof DeProduitRoute
  EnIndexRoute: typeof EnIndexRoute
  EnBlogRoute: typeof EnBlogRoute
  EnConfidentialiteRoute: typeof EnConfidentialiteRoute
  EnFaqRoute: typeof EnFaqRoute
  EnMentionsLegalesRoute: typeof EnMentionsLegalesRoute
  EnProRoute: typeof EnProRoute
  EnProduitRoute: typeof EnProduitRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  ProRoute: typeof ProRoute
  ProduitRoute: typeof ProduitRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit': {
      id: '/produit'
      path: '/produit'
      fullPath: '/produit'
      preLoaderRoute: typeof ProduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/produit': {
      id: '/en/produit'
      path: '/en/produit'
      fullPath: '/en/produit'
      preLoaderRoute: typeof EnProduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/pro': {
      id: '/en/pro'
      path: '/en/pro'
      fullPath: '/en/pro'
      preLoaderRoute: typeof EnProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/mentions-legales': {
      id: '/en/mentions-legales'
      path: '/en/mentions-legales'
      fullPath: '/en/mentions-legales'
      preLoaderRoute: typeof EnMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/faq': {
      id: '/en/faq'
      path: '/en/faq'
      fullPath: '/en/faq'
      preLoaderRoute: typeof EnFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/confidentialite': {
      id: '/en/confidentialite'
      path: '/en/confidentialite'
      fullPath: '/en/confidentialite'
      preLoaderRoute: typeof EnConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/blog': {
      id: '/en/blog'
      path: '/en/blog'
      fullPath: '/en/blog'
      preLoaderRoute: typeof EnBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/produit': {
      id: '/de/produit'
      path: '/de/produit'
      fullPath: '/de/produit'
      preLoaderRoute: typeof DeProduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/pro': {
      id: '/de/pro'
      path: '/de/pro'
      fullPath: '/de/pro'
      preLoaderRoute: typeof DeProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/mentions-legales': {
      id: '/de/mentions-legales'
      path: '/de/mentions-legales'
      fullPath: '/de/mentions-legales'
      preLoaderRoute: typeof DeMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/faq': {
      id: '/de/faq'
      path: '/de/faq'
      fullPath: '/de/faq'
      preLoaderRoute: typeof DeFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/confidentialite': {
      id: '/de/confidentialite'
      path: '/de/confidentialite'
      fullPath: '/de/confidentialite'
      preLoaderRoute: typeof DeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/blog': {
      id: '/de/blog'
      path: '/de/blog'
      fullPath: '/de/blog'
      preLoaderRoute: typeof DeBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/': {
      id: '/de/'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DeIndexRoute: DeIndexRoute,
  DeBlogRoute: DeBlogRoute,
  DeConfidentialiteRoute: DeConfidentialiteRoute,
  DeFaqRoute: DeFaqRoute,
  DeMentionsLegalesRoute: DeMentionsLegalesRoute,
  DeProRoute: DeProRoute,
  DeProduitRoute: DeProduitRoute,
  EnIndexRoute: EnIndexRoute,
  EnBlogRoute: EnBlogRoute,
  EnConfidentialiteRoute: EnConfidentialiteRoute,
  EnFaqRoute: EnFaqRoute,
  EnMentionsLegalesRoute: EnMentionsLegalesRoute,
  EnProRoute: EnProRoute,
  EnProduitRoute: EnProduitRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  ProRoute: ProRoute,
  ProduitRoute: ProduitRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
